version: '3.8'

services:
  mailpit:
    image: axllent/mailpit
    container_name: housnkuh_mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  mailpit-data: